//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildViewer {
    
    
    public partial class TestAnalytics {
        
        /// <summary>
        /// UT_BC2A_CONVERTORS_CmoConvertor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BuildViewer.GraphViewer UT_BC2A_CONVERTORS_CmoConvertor;
        
        /// <summary>
        /// UT_BC2A_CONVERTORS_ISw_BC2A_Convertors_HQModelJc3iedm31_Tests control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BuildViewer.GraphViewer UT_BC2A_CONVERTORS_ISw_BC2A_Convertors_HQModelJc3iedm31_Tests;
    }
}
